### ISSUE TITLE
botがメンションされてないときも反応する

### ISSUE THREAD

**Issue by ouchi2501** [rosso357/GranbuleBot#16]
会話中うざいので、メンションされた時のみ反応するようにする

**Comment by rosso357** [comment]
robot.hearからrobot.respondに修正したら会話中の単語に引っかからなくなった

respond [正規表現]
話しかけられた発言が正規表現にマッチしたらに反応する
（bot名 なんちゃらのなんちゃらとマッチング）

hear [正規表現]
発言が正規表現にマッチしたら（Hubotに呼びかけなくても勝手に）反応する

例
robot.hear /火理想/i, (res) ->
↓修正　
robot.respond /火理想/i, (res) ->

参考URL
https://engineering.otobank.co.jp/entry/2015/06/19/000300
