### ISSUE TITLE
10天衆でも十天衆でもでるようにする

### ISSUE THREAD

**Issue by ouchi2501** [rosso357/GranbuleBot#27]
どちらかというと十天衆感ある
なので十天衆だけでもいいのかも

**Comment by rosso357** [comment]
表記揺れを以下のように修正しました。
10と十はどちらも使えるようにしました。

修正前
robot.respond /10天衆([\s ]?)素材$/i, (res) ->

修正後
robot.respond /(10|十)天衆([\s ]?)素材$/i, (res) ->
