### ISSUE TITLE
dockerでhostとコンテナ上でディレクトを共有できないか調査

### ISSUE THREAD

**Issue by ouchi2501** [rosso357/GranbuleBot#45]
local開発環境にdockerを使用しているが
現状、docker上でvimで開発するかintellij等でコード編集したものを
一度pushしてdockerコンテナ上でpullして確認するダサい状況になっているため
vagrntのasync_folder的なのがないのか確認する

**Comment by ouchi2501** [comment]
`docker run`時に`-v`オプションを指定すればマウントが可能らしい
例
`docker run -ti -d --name gbot -v /Users/hogehoge/granblue-bot/GranbuleBot/:/gran bot`
の様に
`-v <host側のディレクトリ>:<コンテナ側のディレクト>`
のように指定すればおｋ

**Comment by ouchi2501** [comment]
docker-compose.yamlでも指定できるらしいが
個人の開発環境のpathは知ったことではないため-vオプションが共有できたのでクローズ

**Comment by rosso357** [comment]
情報共有ありがとう！
